export {
  APP_WORDING,
  APP_WORDING_BY_LANGUAGE,
  LANGUAGE_DIRECTIONS,
  LANGUAGE_FLAGS,
  LANGUAGE_LABELS,
  RECOMMENDATIONS_WORDING,
  RECOMMENDATIONS_WORDING_BY_LANGUAGE,
  type SupportedLanguage,
} from '../i18n';
